kind = "mobile"
previewPath = "/"
title = "Hinário"
version = "1.0.0"
id = "artifacts/hinario"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/" ]
localPort = 18717

[services.development]
run = "pnpm --filter @workspace/hinario run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/hinario", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/hinario", "run", "serve" ]

[services.env]
PORT = "18717"
BASE_PATH = "/"
